/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package operacionesbasica;

import java.util.Arrays;
import java.util.stream.IntStream;



/**
 *
 * @author jefe
 */
public class NumPrimos extends javax.swing.JFrame {

    /**
     * Creates new form NumPrimos
     */
    public NumPrimos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo = new javax.swing.JLabel();
        lblnumero = new javax.swing.JLabel();
        txtingresarnumero = new javax.swing.JTextField();
        confirmar = new javax.swing.JButton();
        txtconfirmar = new javax.swing.JTextField();
        menoresprimostxt = new javax.swing.JTextField();
        sumaprimostxt = new javax.swing.JTextField();
        raiztxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltitulo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        lbltitulo.setForeground(new java.awt.Color(255, 0, 51));
        lbltitulo.setText("Numeros Primos");

        lblnumero.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        lblnumero.setForeground(new java.awt.Color(51, 0, 255));
        lblnumero.setText("Ingrese el numero");

        confirmar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        confirmar.setForeground(new java.awt.Color(255, 0, 0));
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        txtconfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconfirmarActionPerformed(evt);
            }
        });

        menoresprimostxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoresprimostxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(lblnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(txtingresarnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sumaprimostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtconfirmar, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                                .addComponent(menoresprimostxt))
                            .addComponent(raiztxt, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(confirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lbltitulo)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbltitulo)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtingresarnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtconfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menoresprimostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sumaprimostxt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(raiztxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(confirmar))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
     private boolean esNumeroPrimo(int numero) {
    if (numero <= 1) return false;
    for (int i = 2; i <= Math.sqrt(numero); i++) {
        if (numero % i == 0) return false;
    }
    return true;
}

private int[] obtenerNumerosPrimosMenoresA(int limite) {
    return IntStream.range(2, limite) //genera una secuencia de enteros empezando desde 2 hasta limite - 1//
        .filter(this::esNumeroPrimo)
        .toArray();
}

private double calcularRaizCuadrada(int numero) {
    return Math.sqrt(numero);
}

        
    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        // TODO add your handling code here:
   
        int numero;
    
   
        numero = Integer.parseInt(txtingresarnumero.getText());

        if (numero >= 1 && numero <= 500) {
            String mensaje = esNumeroPrimo(numero) ? " es un número primo" : " no es un número primo";
            txtconfirmar.setText(numero + mensaje);

            int[] primosMenores = obtenerNumerosPrimosMenoresA(numero);
            int sumaPrimosMenores = Arrays.stream(primosMenores).sum();
            double raizCuadradaSuma = calcularRaizCuadrada(sumaPrimosMenores);

            menoresprimostxt.setText("Los números primos menores al número ingresado son: " +
                    Arrays.toString(primosMenores));
            sumaprimostxt.setText("Su suma es: " + sumaPrimosMenores);
            raiztxt.setText("Su raíz cuadrada es: " + raizCuadradaSuma);
        } else {
            // El número está fuera del rango permitido
            txtconfirmar.setText("Por favor, ingrese un número entre 1 y 500");
            // Limpiar resultados en caso de número fuera de rango
            menoresprimostxt.setText("");
            sumaprimostxt.setText("");
            raiztxt.setText("");
        }
    
    }//GEN-LAST:event_confirmarActionPerformed
    
    
    private void txtconfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconfirmarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconfirmarActionPerformed

    private void menoresprimostxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoresprimostxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menoresprimostxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NumPrimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NumPrimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NumPrimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NumPrimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NumPrimos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel lblnumero;
    private javax.swing.JLabel lbltitulo;
    private javax.swing.JTextField menoresprimostxt;
    private javax.swing.JTextField raiztxt;
    private javax.swing.JTextField sumaprimostxt;
    private javax.swing.JTextField txtconfirmar;
    private javax.swing.JTextField txtingresarnumero;
    // End of variables declaration//GEN-END:variables
}
